import { NextResponse } from "next/server";
import { getSmtpConfig, sendSmtpEmail } from "@/lib/smtp-mailer";

export const runtime = "nodejs";

type NotificationBody = {
  details?: Record<string, string | number | undefined>;
  subject?: string;
  type?: string;
};

export async function POST(request: Request) {
  const body = (await request.json()) as NotificationBody;
  const adminEmail = process.env.ADMIN_EMAIL || "focusjournal786@gmail.com";
  const subject = String(body.subject || "CORE X FITNESS Notification").trim();
  const details = body.details || {};
  const message = [
    `Type: ${body.type || "website"}`,
    "",
    ...Object.entries(details).map(([key, value]) => `${key}: ${value ?? ""}`),
    "",
    "This notification was generated by the CORE X FITNESS website."
  ].join("\n");
  const config = getSmtpConfig();

  if (!config) {
    return NextResponse.json({
      ok: false,
      skipped: true,
      reason: "SMTP is not configured.",
      to: adminEmail
    });
  }

  await sendSmtpEmail(config, {
    subject,
    text: message,
    to: adminEmail
  });

  return NextResponse.json({ ok: true });
}
